cygnodePath="$(cygpath --mixed -- "$(pwd)")"
nodejsPath="$(cygpath --mixed -- "$(dirname "$(which node)")")"
nodePath="$nodejsPath/nodeImpl.exe"
execPath="$nodejsPath/node.exe"
confPath="$execPath.conf"
